version: '3'

services:
  php:
    build: .
    environment:
      - APACHE_LOG_DIR=/var/log/httpd
    volumes:
      - ${PROJECT_DIR}:/var/www/html
      - ./httpd_log:/var/log/httpd
    ports:
      - 8081:80
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - ./mysql/lib/mysql:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/log:/var/log/mysql
      - ./mysql/dump:/tmp/dump
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports: 
      - 3310:3306
    expose:
      - 3310
